{"uuid": "2d312e0c-5699-485c-b6ca-7c712aed391b", "children": ["acdad381-0763-4c55-a6da-34dcf18e057e"], "befores": [{"name": "browser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home\n\n", "trace": "  File \"/home/max/venv/lib/python3.6/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/max/venv/lib/python3.6/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/max/venv/lib/python3.6/site-packages/_pytest/fixtures.py\", line 932, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/home/max/logging_in_PO/conftest.py\", line 33, in browser\n    driver = webdriver.Chrome(desired_capabilities=caps)\n  File \"/home/max/venv/lib/python3.6/site-packages/selenium/webdriver/chrome/webdriver.py\", line 73, in __init__\n    self.service.start()\n  File \"/home/max/venv/lib/python3.6/site-packages/selenium/webdriver/common/service.py\", line 83, in start\n    os.path.basename(self.path), self.start_error_message)\n"}, "start": 1632393868102, "stop": 1632393868106}], "start": 1632393868102, "stop": 1632393868204}