{"uuid": "b261e800-9405-4f2c-8aae-c13e53b56ae8", "children": ["d0515a27-a9c8-41ac-98fa-2125aa1f0ecf"], "befores": [{"name": "browser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home\n\n", "trace": "  File \"/home/max/venv/lib/python3.6/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/max/venv/lib/python3.6/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/max/venv/lib/python3.6/site-packages/_pytest/fixtures.py\", line 932, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/home/max/logging_in_PO/conftest.py\", line 33, in browser\n    driver = webdriver.Chrome(desired_capabilities=caps)\n  File \"/home/max/venv/lib/python3.6/site-packages/selenium/webdriver/chrome/webdriver.py\", line 73, in __init__\n    self.service.start()\n  File \"/home/max/venv/lib/python3.6/site-packages/selenium/webdriver/common/service.py\", line 83, in start\n    os.path.basename(self.path), self.start_error_message)\n"}, "start": 1632393868206, "stop": 1632393868208}], "start": 1632393868206, "stop": 1632393868307}